version: '3.3'
volumes:
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/db'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090